# Generated by Django 5.0.11 on 2025-09-05 05:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='模板名称')),
                ('type', models.CharField(choices=[('system', '系统通知'), ('achievement', '成就通知'), ('reminder', '学习提醒'), ('social', '社区消息'), ('quiz', '测验通知'), ('security', '安全提醒')], max_length=20, verbose_name='通知类型')),
                ('title_template', models.CharField(max_length=200, verbose_name='标题模板')),
                ('message_template', models.TextField(verbose_name='消息模板')),
                ('priority', models.CharField(choices=[('low', '低'), ('normal', '普通'), ('high', '高'), ('urgent', '紧急')], default='normal', max_length=10, verbose_name='优先级')),
                ('action_url_template', models.CharField(blank=True, max_length=500, verbose_name='操作链接模板')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '通知模板',
                'verbose_name_plural': '通知模板',
                'db_table': 'notification_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('system', '系统通知'), ('achievement', '成就通知'), ('reminder', '学习提醒'), ('social', '社区消息'), ('quiz', '测验通知'), ('security', '安全提醒')], default='system', max_length=20, verbose_name='通知类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('message', models.TextField(verbose_name='消息内容')),
                ('priority', models.CharField(choices=[('low', '低'), ('normal', '普通'), ('high', '高'), ('urgent', '紧急')], default='normal', max_length=10, verbose_name='优先级')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('action_url', models.URLField(blank=True, null=True, verbose_name='操作链接')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_611c58_idx'), models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx'), models.Index(fields=['type', '-created_at'], name='notificatio_type_d2e2f1_idx')],
            },
        ),
    ]
