version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    volumes:
      - ./backend:/app
      - ~/.gitconfig:/root/.gitconfig
      - ~/.ssh:/root/.ssh
      - ~/.git-credentials:/root/.git-credentials
    ports:
      - "8000:8000"
    networks:
      - dev_network
    environment:
      - DB_ENGINE=django.db.backends.mysql
      - DB_NAME=mydatabase
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_HOST=mysql
      - DB_PORT=3306
      - NEO4J_URI=neo4j://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      - PYTHONUNBUFFERED=1
    depends_on:
      - mysql
      - neo4j

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    volumes:
      - ./frontend:/app
      - node_modules_volume:/app/node_modules
    ports:
      - "3000:3000"
    networks:
      - dev_network
    environment:
      - CHOKIDAR_USEPOLLING=true

  neo4j:
    image: neo4j:latest
    volumes:
      - ./db/neo4j:/data
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - dev_network
    environment:
      - NEO4J_AUTH=neo4j/password

  mysql:
    image: mysql:8
    volumes:
      - ./db/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - dev_network
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

networks:
  dev_network:
    driver: bridge

volumes:
  node_modules_volume:
#    以下为流水线测试7