# Generated by Django 5.0.11 on 2025-09-05 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_type', models.CharField(max_length=100, verbose_name='场景类型')),
                ('difficulty', models.CharField(choices=[('easy', '简单'), ('medium', '中等'), ('hard', '困难')], max_length=10, verbose_name='难度')),
                ('mode', models.CharField(choices=[('mixed', '真假混合'), ('fake_only', '纯假学习')], max_length=20, verbose_name='模式')),
                ('score', models.IntegerField(verbose_name='最终得分')),
                ('conversation_rounds', models.IntegerField(verbose_name='对话轮次')),
                ('end_reason', models.CharField(choices=[('score_too_low', '分数过低'), ('perfect_score', '满分'), ('max_rounds', '达到最大轮次'), ('manual_end', '手动结束')], max_length=20, verbose_name='结束原因')),
                ('report_data', models.JSONField(help_text='包含标题、消息、建议和对话记录', verbose_name='报告数据')),
                ('completed_at', models.DateTimeField(verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '测试记录',
                'verbose_name_plural': '测试记录',
                'ordering': ['-completed_at'],
            },
        ),
    ]
