name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: [self-hosted, main]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Use npm mirror in China
        run: npm config set registry https://registry.npmmirror.com/

      - name: Install and build frontend
        working-directory: frontend
        run: |
          npm ci
          npm run build

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libmysqlclient-dev

      - name: Configure pip mirror
        run: |
          python -m pip install --upgrade pip
          pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple

      - name: Install backend requirements
        run: pip install -r backend/requirements.txt

      - name: Compile Python files
        run: python -m compileall backend

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: [self-hosted, main]
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            cd /path/to/AntiFraudKnowledge
            git pull
            docker compose pull
            docker compose up -d
