name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: [self-hosted, main]

    steps:
      # 只给 GitHub 域名走代理，解决拉代码超时
      - name: Setup Git proxy for GitHub only
        run: |
          git config --global http.https://github.com.proxy http://127.0.0.1:7890
          git config --global http.https://raw.githubusercontent.com.proxy http://127.0.0.1:7890
          git config --global http.https://objects.githubusercontent.com.proxy http://127.0.0.1:7890
          git config --global http.https://actions.githubusercontent.com.proxy http://127.0.0.1:7890

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      # ---------- Frontend ----------
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Use npm mirror in China
        run: npm config set registry https://registry.npmmirror.com/

      - name: Install and build frontend
        working-directory: frontend
        run: |
          npm ci
          npm run build

      # ---------- Backend ----------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: backend/requirements.txt

      - name: Install system dependencies (for mysqlclient)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config default-libmysqlclient-dev
          # 若连接 MariaDB，请改为：
          # sudo apt-get install -y build-essential pkg-config libmariadb-dev-compat libmariadb-dev

      - name: Configure pip mirror (CN)
        run: |
          python -m pip install --upgrade pip
          pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple

      - name: Install backend requirements
        working-directory: backend
        run: pip install -r requirements.txt

      - name: Compile Python files
        run: python -m compileall backend

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: [self-hosted, main]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      # 如果 compose 文件在仓库根目录，working-directory 写成 "."
      # 如果你要部署到固定目录（非工作区），把 rsync 打开即可
      # - name: Sync to release directory (optional)
      #   run: |
      #     rsync -a --delete ./ /srv/AntiFraudKnowledge/

      - name: Deploy locally with Docker Compose
        working-directory: .
        run: |
          # 如果需要登录私有镜像仓库，在这里 docker login
          docker compose pull
          docker compose up -d --remove-orphans
          docker system prune -f

      # 可选：健康检查/打印日志
      - name: Check containers
        run: |
          docker ps
          docker compose logs -n 100 || true
